In [47]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical


In [37]:
#전처리할 텍스트
text = '해보지 않으면 해낼 수 없다'

In [38]:
# 텍스트를 토큰화 함 -> text_to_word_sequence

result = text_to_word_sequence(text)
print('원본 : ', text)
print('토큰 처리한 결과 : ', result)

원본 :  해보지 않으면 해낼 수 없다
토큰 처리한 결과 :  ['해보지', '않으면', '해낼', '수', '없다']


In [39]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딜러닝에서 사용할 수 있습니다.']

In [40]:
token = Tokenizer()
token.fit_on_texts(docs)

In [41]:
print('\n단어 카운트:\n', token.word_counts)
print('텍스트의 단어는 : ', token.word_counts['텍스트의'], '회 나옴')


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 1), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('딜러닝에서', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])
텍스트의 단어는 :  2 회 나옴


In [42]:
print('\n문장 카운트: ', token.document_count)


문장 카운트:  3


In [43]:
print(' 각 단어가 몇개의 문장에 포함되어 있는지? : ', token.word_docs)
print(' 각 단어가 몇개의 문장에 포함되어 있는지? : ', token.word_index)

 각 단어가 몇개의 문장에 포함되어 있는지? :  defaultdict(<class 'int'>, {'먼저': 1, '단어를': 1, '텍스트의': 2, '각': 1, '나누어': 1, '토큰화합니다': 1, '인식됩니다': 1, '토큰화해야': 1, '단어로': 1, '딥러닝에서': 1, '수': 1, '있습니다': 1, '사용할': 1, '딜러닝에서': 1, '토큰화한': 1, '결과는': 1})
 각 단어가 몇개의 문장에 포함되어 있는지? :  {'텍스트의': 1, '먼저': 2, '각': 3, '단어를': 4, '나누어': 5, '토큰화합니다': 6, '단어로': 7, '토큰화해야': 8, '딥러닝에서': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '딜러닝에서': 13, '사용할': 14, '수': 15, '있습니다': 16}


In [44]:
# 각 단어의 인덱스만 추출

print(token.texts_to_sequences(docs))

[[2, 1, 3, 4, 5, 6], [1, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16]]


In [48]:
text1 = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token1 = Tokenizer()
token1.fit_on_texts([text1])

print(token1.word_index)
x = token1.texts_to_sequences([text1])

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [49]:
to_categorical(x, len(token1.word_index) + 1)

array([[[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]]], dtype=float32)

In [52]:
# %load tensor.py
# from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
# from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import matplotlib.pyplot as plt
import numpy as np

In [56]:
reviews = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]
classes = np.array([1,1,1,1,1,0,0,0,0,0])


In [58]:
# 1. 토큰화

token = Tokenizer()
token.fit_on_texts(reviews) # 리뷰 단어 토큰화

print("단어의 인덱스 : ", token.word_index,'\n', len(token.word_index)) #총 단어수

단어의 인덱스 :  {'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20} 
 20


In [59]:
# 토큰한 결과를 가지고 인덱스로 문장을 변환
x = token.texts_to_sequences(reviews) # 문장의 단어를 token한 결과 단어의 인덱스로 변환

print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [60]:
# 각 문장의 단어의 개수가 다름 -> 문장의 단어의 개수를 동일하게 적용
padd_x = pad_sequences(x, 4) # x를 각 문장의 단서 수가 4개로 통일 : 단어 수가 적으면 앞에 0 추가, 많으면 자름
print(padd_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [61]:
# 딥러닝 모델 생성
model = Sequential()
model.add(Embedding(len(token.word_index) + 1, 8, input_length = 4)) # 총 단어수, 임베딩 사이즈, 입력 단어수
model.add(Flatten()) # 다음 레이어를 위해 1차원 배열로 변환
model.add(Dense(1,activation = 'sigmoid')) # 긍정 또는 부정이므로 활성함수는 sigmoid
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [62]:
# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# 모델 실행
model.fit(padd_x, classes, epochs= 20)
print('Accuracy : ', model.evaluate(padd_x, classes)[1])

Epoch 1/20
1/1 [==============================] - 3s 3s/step - loss: 0.6971 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6949 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6928 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6906 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6885 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6863 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6842 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6821 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6800 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6779 - accuracy: 0.9000
Epoch 11/20
1/1 [=======================